### ISSUE TITLE
New model never shows up in Studio

### ISSUE THREAD

**Issue by haimat** [iterative/studio-support#79]
I wanted to add a new model to the Studio model registry. Thus I have entered all the details like name etc. in the "Add a new model" page in Studio and hit the "Commit changes" button. After that the following message appears:

![image](https://user-images.githubusercontent.com/6633976/224550892-562692e1-e92c-4fc4-a14f-1eb19daab809.png)

I have tried it both ways, to commit directly to the "main" branch, as well as to create a new branch and PR. However, in both cases nothing happened. This was Friday, now two days later still no new model in the registry. I tried it now a third time, but still no model. Also nothing on Github, no PR and no commit.

Could it be that my "new model" jobs are still waiting in your queue or something?

**Comment by shcheklein** [comment]
I've tried to reproduce this, here is the PR it created https://github.com/shcheklein/example-get-started/pull/1

@haimat could you sceenshot the settings for the Add model dialogue, or describe the details - e.g. - do you create a PR or try to commit directly to a branch? do use the latest commit, or some commit in between? any other fields - e.g. labels, descriptions, etc

I'm also looking into the logs to see the job status.

**Comment by haimat** [comment]
@shcheklein I have just sent you a screenshot of the "new model" dialog.
I tried with both, directly adding to the main branch and creating a new branch with PR.
Always the same result - nothing happens, neither in Studio nor on Github.

**Comment by shcheklein** [comment]
Yep, thanks! Looking into this ...

**Comment by haimat** [comment]
Thanks 👍



--
Matthias F. Brandstetter
***@***.***
________________________________

**Comment by shcheklein** [comment]
From what I see in the logs. No jobs are stuck in the queue.

- the main branch is protected, you can't commit to it directly.
- there is a weird error for this workflow `Not allowed to edit workflow file on GitHub` (it happens when `.github` files are touched, but I don't think they should be in this case ... but let me know if something comes to your mind). I'm looking into this ...

Anyways - we need to show an error message in this case cc @tapadipti @jellebouwman

**Comment by haimat** [comment]
@shcheklein Thanks for your analysis. The main branch is protected, that's correct, but I guess Studio should tell me that this is not an option, right? But even more important: I can also not create another branch via PR - if I select that option then also nothing happens in Studio and an Github.

So if these both options are not possible, what else can/should I do in order to create a new model tag on Github via Studio?

PS: I don't see why Studio would complain about not being able to edit my workflow on Github either. Why would it ever want to touch a file under `.github`?

**Comment by haimat** [comment]
Update: I just tried it once more, this time again with a new branch and a PR - and now it worked.
Fun fact: Now also all my previous three attempts show up on the Studio model page:

![image](https://user-images.githubusercontent.com/6633976/224565967-eb3e473a-2f34-415c-b5d2-272f0fab28ab.png)

So beside missing warning messages in Studio the problem itself has been solved now as it seems.
Shall I close this issue?

**Comment by shcheklein** [comment]
> PS: I don't see why Studio would complain about not being able to edit my workflow on Github either. Why would it ever want to touch a file under .github?

Yes, that's what I'm looking into. This is weird, probably it's a misleading error, but something causing GitHub to reject even when Studio is trying to create a new branch.

> So beside missing warning messages in Studio the problem itself has been solved now as it seems.

It's still an issue with these missing messages + it's not clear why it didn't work for you with a PR before. Let's keep it open for a while.

It's less critical though now, it's good that we managed to move forward and thank you for the feedback.

**Comment by haimat** [comment]
Sure, thanks for your support.
Now back to the [real issue of fetching that model file via DVC](https://github.com/iterative/studio-support/issues/75), why we came to all this in the first place :)

**Comment by shcheklein** [comment]
Yep, let's followup on that thread now as we got there.

On this issue - could you please check if one of the commits in the main branch touched the `.github` files? could you share its hash?

**Comment by haimat** [comment]
> On this issue - could you please check if one of the commits in the main branch touched the `.github` files? could you share its hash?

Nope, none of the related commits in the main branch touched any of the `.github` files.

**Comment by shcheklein** [comment]
@haimat could you please check specifically this commit `a59056c88dc518e99e93ac50ea35752f1ab38c11` ? We've seen this before in MR and have an internal issue for this - when on GH you are trying to touch in any way (e.g. create a model version tag) a commit that has anything to do with a workflow file it raises an error. Most like this is what is happening here tbh.

**Comment by haimat** [comment]
> @haimat could you please check specifically this commit `a59056c88dc518e99e93ac50ea35752f1ab38c11` ?

Nope, just checked it - that commit touched exactly one `.py` file, that's it:

![image](https://user-images.githubusercontent.com/6633976/224675813-6429f957-b9cb-4356-9349-c76c2e4915c6.png)

**Comment by shcheklein** [comment]
Okay, we have added a bit of logs to catch this situation.

I'll also create a ticket to fix the issue when the action seems to be stuck (when there are no models yet).

We've improved also some messages- should be better now.

Thanks for the report @haimat !
